#benützt das image nginx
FROM nginx 

# legt den ort für nginx html files fest
WORKDIR /usr/share/nginx/html

# kopiert das index.html file zum nginx server
COPY index.html .

# benützt den port 80
EXPOSE 80

