FROM mariadb

# Umgebungsvariablen für Benutzername und Passwort definieren
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=mysql
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=password

# Port 3306 exponieren
EXPOSE 3306
